"use strict";

var routeHelper = require('loopback-explorer/lib/route-helper');

var convertAcceptsToSwagger = routeHelper.convertAcceptsToSwagger;
routeHelper.convertAcceptsToSwagger = function (route, classDef) {
    var accepts = convertAcceptsToSwagger(route, classDef);
    // Filter out parameters that are generated from the incoming request,
    // or generated by functions that use those resources.
    accepts = accepts.filter(function(arg){
        return !arg.http || !arg.http.source || 'body' === arg.http.source;
    });

    return accepts;
};