"use strict";

var _contains = require('lodash.contains');
var routeHelper = require('loopback-explorer/lib/route-helper');

var convertAcceptsToSwagger = routeHelper.convertAcceptsToSwagger;
routeHelper.convertAcceptsToSwagger = function (route, classDef) {
    var accepts = convertAcceptsToSwagger(route, classDef);
    // Filter out parameters that are generated from the incoming request,
    // or generated by functions that use those resources.
    accepts = accepts.filter(function(arg){
        if (!arg.http) return true;
        return !arg.http.source || _contains(['body'], arg.http.source);
    });

    return accepts;
};